name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the issue
      placeholder: |
        1. Configure with...
        2. Run command...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Provide your configuration (remove sensitive data)
      placeholder: |
        ```
        MCP_TRANSPORT=stdio
        MCP_READ_ONLY=true
        OAUTH_PROVIDER=github
        ```
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any relevant error messages or logs
      placeholder: |
        ```
        Error: ...
        ```
      render: shell
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the MCP server are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: transport
    attributes:
      label: Transport Type
      description: Which transport are you using?
      options:
        - stdio
        - sse
        - streamable-http
        - http-server
        - multi-transport-server
    validations:
      required: true

  - type: dropdown
    id: oauth
    attributes:
      label: OAuth Provider (if applicable)
      description: Which OAuth provider are you using?
      options:
        - Not using OAuth
        - GitHub
        - Google
        - Azure AD
        - Okta
        - Auth0
        - Custom
    validations:
      required: false

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: Run `node --version`
      placeholder: e.g., v18.17.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you running on?
      placeholder: e.g., Ubuntu 22.04, macOS 14.0, Windows 11
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all relevant configuration details
          required: true
        - label: I have removed any sensitive information from logs/config
          required: true

