/**
 * AUTO-GENERATED FILE — do not edit by hand.
 *
 * Generated by scripts/generate-field-schemas.mjs from the LogicMonitor Swagger v3 spec.
 * Run `npm run generate:field-schemas` to regenerate after API changes.
 *
 * Maps tools to their Swagger response model and the set of valid `fields` names,
 * enabling strict validation of the optional `fields` parameter.
 */

/** Schema name -> the complete set of valid field names from the Swagger model. */
export const FIELD_SCHEMAS: Record<string, readonly string[]> = {
  Device: ['autoBalancedCollectorGroupId', 'autoProperties', 'autoPropsAssignedOn', 'autoPropsUpdatedOn', 'awsState', 'azureState', 'collectorDescription', 'containsMultiValue', 'createdOn', 'currentCollectorId', 'currentLogCollectorId', 'customProperties', 'deletedTimeInMs', 'description', 'deviceType', 'disableAlerting', 'displayName', 'enableNetflow', 'gcpState', 'hostGroupIds', 'hostStatus', 'id', 'inheritedProperties', 'isPreferredLogCollectorConfigured', 'lastDataTime', 'lastRawdataTime', 'link', 'logCollectorDescription', 'logCollectorGroupId', 'logCollectorGroupName', 'logCollectorId', 'name', 'netflowCollectorDescription', 'netflowCollectorGroupId', 'netflowCollectorGroupName', 'netflowCollectorId', 'op', 'preferredCollectorGroupId', 'preferredCollectorGroupName', 'preferredCollectorId', 'relatedDeviceId', 'resourceIds', 'rolePrivileges', 'scanConfigId', 'syntheticsCollectorIds', 'systemProperties', 'toDeleteTimeInMs', 'type', 'upTimeInSeconds', 'updatedOn', 'userPermission'],
  DeviceGroup: ['appliesTo', 'awsRegionsInfo', 'awsTestResult', 'awsTestResultCode', 'azureRegionsInfo', 'azureTestResult', 'azureTestResultCode', 'createdOn', 'customProperties', 'defaultAutoBalancedCollectorGroupId', 'defaultCollectorDescription', 'defaultCollectorGroupDescription', 'defaultCollectorGroupId', 'defaultCollectorId', 'description', 'disableAlerting', 'effectiveAlertEnabled', 'enableNetflow', 'extra', 'fullPath', 'gcpRegionsInfo', 'gcpTestResult', 'gcpTestResultCode', 'groupStatus', 'groupType', 'hasNetflowEnabledDevices', 'id', 'name', 'numOfAWSDevices', 'numOfAzureDevices', 'numOfDirectDevices', 'numOfDirectSubGroups', 'numOfGcpDevices', 'numOfHosts', 'numOfKubernetesDevices', 'numOfOciDevices', 'ociRegionsInfo', 'ociTestResult', 'ociTestResultCode', 'parentId', 'propertyChangeWarningMessage', 'rolePrivileges', 'saasTestResult', 'saasTestResultCode', 'subGroups', 'userPermission'],
  Alert: ['SDT', 'ackComment', 'acked', 'ackedBy', 'ackedEpoch', 'adAlert', 'adAlertDesc', 'alertExternalTicketUrl', 'alertGroupEntityValue', 'alertQuery', 'alertTriggerValue', 'alertValue', 'anomaly', 'chain', 'chainId', 'clearExpr', 'clearValue', 'cleared', 'context', 'dataPointId', 'dataPointName', 'dependencyRole', 'dependencyRoutingState', 'enableAnomalyAlertGeneration', 'enableAnomalyAlertSuppression', 'endEpoch', 'id', 'instanceDescription', 'instanceId', 'instanceName', 'internalId', 'lastUpdatedOnEpoch', 'logMetaData', 'logPartition', 'monitorObjectGroups', 'monitorObjectId', 'monitorObjectName', 'monitorObjectType', 'nextRecipient', 'receivedList', 'resourceId', 'resourceTemplateId', 'resourceTemplateName', 'resourceTemplateType', 'rule', 'ruleId', 'sdtIds', 'sdted', 'sessionId', 'severity', 'startEpoch', 'subChainId', 'suppressDesc', 'suppressor', 'tenant', 'threshold', 'type'],
  Dashboard: ['defaultDashboardFilters', 'description', 'fullName', 'groupFullPath', 'groupId', 'groupName', 'id', 'name', 'overwriteGroupFields', 'owner', 'sharable', 'template', 'userPermission', 'widgetTokens', 'widgetsConfig'],
  DashboardGroup: ['dashboards', 'description', 'fullPath', 'id', 'name', 'numOfDashboards', 'numOfDirectDashboards', 'numOfDirectSubGroups', 'parentId', 'template', 'userPermission', 'widgetTokens'],
  Widget: ['dashboardId', 'description', 'id', 'interval', 'isSupportCustomProperty', 'lastUpdatedBy', 'lastUpdatedOn', 'name', 'supportCustomProperty', 'theme', 'timescale', 'type', 'userPermission'],
  Website: ['checkpoints', 'collectors', 'description', 'disableAlerting', 'domain', 'globalSmAlertCond', 'groupId', 'id', 'individualAlertLevel', 'individualSmAlertEnable', 'isInternal', 'lastUpdated', 'name', 'overallAlertLevel', 'pollingInterval', 'properties', 'rolePrivileges', 'status', 'steps', 'stopMonitoring', 'stopMonitoringByFolder', 'template', 'testLocation', 'transition', 'type', 'useDefaultAlertSetting', 'useDefaultLocationSetting', 'userPermission'],
  WebsiteGroup: ['description', 'disableAlerting', 'fullPath', 'hasWebsitesDisabled', 'id', 'name', 'numOfDirectSubGroups', 'numOfDirectWebsites', 'numOfWebsites', 'parentId', 'properties', 'rolePrivileges', 'stopMonitoring', 'testLocation', 'userPermission'],
  Collector: ['ackComment', 'acked', 'ackedBy', 'ackedOn', 'ackedOnLocal', 'agentConfFields', 'arch', 'automaticUpgradeInfo', 'backupAgentId', 'bearerToken', 'build', 'calculatedThreshold', 'canDowngrade', 'canDowngradeReason', 'clearSent', 'collectorConf', 'collectorDeviceId', 'collectorGroupId', 'collectorGroupName', 'collectorList', 'collectorSize', 'collectorType', 'confVersion', 'config', 'copyUrl', 'createdOn', 'createdOnLocal', 'customProperties', 'description', 'downloadUrl', 'ea', 'enableFailBack', 'enableFailOverOnCollectorDevice', 'enableLMLogs', 'encodedConfigData', 'errorMsg', 'escalatingChainId', 'format', 'hasFailOverDevice', 'hostname', 'id', 'inSDT', 'isAdminAccount', 'isDown', 'isEncoded', 'isLmlogsSyslogEnabled', 'lastSentNotificationOn', 'lastSentNotificationOnLocal', 'needAutoCreateCollectorDevice', 'netscanVersion', 'nextRecipient', 'nextUpgradeInfo', 'numberOfHosts', 'numberOfInstances', 'numberOfSDTs', 'onetimeDowngradeInfo', 'onetimeUpgradeInfo', 'otelId', 'otelVersion', 'platform', 'predefinedConfig', 'previousVersion', 'resendIval', 'sbproxyConf', 'specifiedCollectorDeviceGroupId', 'status', 'suppressAlertClear', 'syntheticsEnabled', 'upTime', 'updatedOn', 'updatedOnLocal', 'userChangeOn', 'userChangeOnLocal', 'userPermission', 'userVisibleHostsNum', 'watchdogConf', 'watchdogUpdatedOn', 'watchdogUpdatedOnLocal', 'wrapperConf'],
  CollectorGroup: ['autoBalance', 'autoBalanceInstanceCountThreshold', 'autoBalanceStrategy', 'calThreshold', 'createOn', 'customProperties', 'description', 'highestPriorityCollectorStatus', 'id', 'mismatchVersion', 'name', 'numOfCollectors', 'numOfHosts', 'numOfInstances', 'platform', 'propertyForBalancing', 'propertyForBalancingLastUpdatedOn', 'propertyForBalancingUpdateLockedUptoMS', 'userPermission'],
  Admin: ['acceptEULA', 'acceptEULAOn', 'adminGroupIds', 'apiTokens', 'apionly', 'contactMethod', 'createdBy', 'email', 'firstName', 'forcePasswordChange', 'id', 'immediateForceLogout', 'inactiveSessionTimeoutInSeconds', 'lastAccessOn', 'lastAction', 'lastActionOn', 'lastActionOnLocal', 'lastAuthIp', 'lastLoginOn', 'lastName', 'note', 'password', 'persistentSessionEnabled', 'phone', 'roles', 'smsEmail', 'smsEmailFormat', 'status', 'tenantId', 'timezone', 'trainingEmail', 'twoFAEnabled', 'userPermission', 'userType', 'username', 'viewPermission'],
  Role: ['acctRequireTwoFA', 'associatedUserCount', 'customHelpLabel', 'customHelpURL', 'description', 'enableRemoteSessionInCompanyLevel', 'id', 'name', 'privileges', 'requireEULA', 'roleGroupId', 'twoFARequired', 'userPermission'],
  DataSource: ['accessGroupIds', 'accessGroups', 'adParameters', 'appliesTo', 'auditVersion', 'autoDiscoveryConfig', 'checksum', 'collectInterval', 'collectMethod', 'collectorAttribute', 'dataPoints', 'description', 'displayName', 'enableAutoDiscovery', 'enableEriDiscovery', 'eriDiscoveryConfig', 'eriDiscoveryInterval', 'group', 'hasMultiInstances', 'id', 'installationMetadata', 'isInUse', 'lineageId', 'name', 'originRegistryId', 'payloadVersion', 'tags', 'technology', 'useWildValueAsUUID', 'version'],
  EventSource: ['accessGroupIds', 'accessGroups', 'alertBodyTemplate', 'alertEffectiveIval', 'alertLevel', 'alertSubjectTemplate', 'appliesTo', 'auditVersion', 'checksum', 'clearAfterAck', 'collector', 'description', 'eventSource', 'eventSourceFilters', 'filters', 'group', 'id', 'installationMetadata', 'isInUse', 'lineageId', 'name', 'originRegistryId', 'suppressDuplicatesES', 'tags', 'technology', 'version'],
  ConfigSource: ['accessGroupIds', 'accessGroups', 'adParameters', 'appliesTo', 'auditVersion', 'autoDiscoveryConfig', 'checksum', 'collectInterval', 'collectMethod', 'collectorAttribute', 'configChecks', 'description', 'displayName', 'enableAutoDiscovery', 'fileFormat', 'group', 'hasMultiInstances', 'id', 'installationMetadata', 'isInUse', 'lineageId', 'name', 'originRegistryId', 'tags', 'technology', 'timestampFormat', 'version'],
  SDT: ['admin', 'comment', 'defaultValue', 'duration', 'endDateTime', 'endDateTimeOnLocal', 'endHour', 'endMinute', 'hour', 'id', 'isEffective', 'minute', 'monthDay', 'sdtType', 'startDateTime', 'startDateTimeOnLocal', 'timezone', 'type', 'weekDay', 'weekOfMonth'],
  OpsNote: ['createdBy', 'happenOnInSec', 'id', 'note', 'scopes', 'tags'],
  Report: ['customReportTypeId', 'customReportTypeName', 'delivery', 'description', 'enableViewAsOtherUser', 'format', 'groupId', 'id', 'lastGenerateOn', 'lastGeneratePages', 'lastGenerateSize', 'lastmodifyUserId', 'lastmodifyUserName', 'name', 'recipients', 'reportLinkExpire', 'reportLinkNum', 'schedule', 'scheduleTimezone', 'type', 'userPermission'],
  RecipientGroup: ['description', 'groupName', 'id', 'recipients'],
  AlertRule: ['datapoint', 'datasource', 'deviceGroups', 'devices', 'escalatingChain', 'escalatingChainId', 'escalationInterval', 'id', 'instance', 'levelStr', 'name', 'priority', 'resourceProperties', 'sendAnomalySuppressedAlert', 'suppressAlertAckSdt', 'suppressAlertClear'],
  EscalationChain: ['ccDestinations', 'description', 'destinations', 'enableThrottling', 'id', 'inAlerting', 'name', 'throttlingAlerts', 'throttlingPeriod'],
};

/** Tool name -> the schema in FIELD_SCHEMAS used to validate its `fields` parameter. */
export const TOOL_FIELD_SCHEMA: Record<string, string> = {
  list_resources: 'Device',
  get_resource: 'Device',
  list_resource_groups: 'DeviceGroup',
  get_resource_group: 'DeviceGroup',
  list_alerts: 'Alert',
  get_alert: 'Alert',
  list_dashboards: 'Dashboard',
  get_dashboard: 'Dashboard',
  list_dashboard_groups: 'DashboardGroup',
  get_dashboard_group: 'DashboardGroup',
  list_widgets: 'Widget',
  get_widget: 'Widget',
  list_websites: 'Website',
  get_website: 'Website',
  list_website_groups: 'WebsiteGroup',
  get_website_group: 'WebsiteGroup',
  list_collectors: 'Collector',
  get_collector: 'Collector',
  list_collector_groups: 'CollectorGroup',
  get_collector_group: 'CollectorGroup',
  list_users: 'Admin',
  get_user: 'Admin',
  list_roles: 'Role',
  get_role: 'Role',
  list_datasources: 'DataSource',
  get_datasource: 'DataSource',
  list_eventsources: 'EventSource',
  get_eventsource: 'EventSource',
  list_configsources: 'ConfigSource',
  get_configsource: 'ConfigSource',
  list_sdts: 'SDT',
  get_sdt: 'SDT',
  list_opsnotes: 'OpsNote',
  get_opsnote: 'OpsNote',
  list_reports: 'Report',
  get_report: 'Report',
  list_recipient_groups: 'RecipientGroup',
  get_recipient_group: 'RecipientGroup',
  list_alert_rules: 'AlertRule',
  get_alert_rule: 'AlertRule',
  list_escalation_chains: 'EscalationChain',
  get_escalation_chain: 'EscalationChain',
};
