/* eslint-disable */
/**
 * AUTO-GENERATED FILE — do not edit by hand.
 *
 * Generated by scripts/generate-fixtures.mjs from the LogicMonitor (LM) Swagger
 * v3 spec. Run `npm run generate:fixtures` to regenerate after API changes.
 *
 * Each entry is a single, schema-accurate example object for an LM resource
 * model, used by the test mocks (see fixtures-helpers.ts) so unit tests assert
 * against payloads shaped like the real API. Values are deterministic
 * placeholders (ids = 1, epoch timestamps = 1700000000, enums = first member).
 */

/** Model name -> a canonical example object with real Swagger field names. */
export const LM_FIXTURES = {
  Admin: {
    "acceptEULA": true,
    "acceptEULAOn": 1700000000,
    "adminGroupIds": "[1,2,3]",
    "apiTokens": [
      {
        "accessId": "sample-accessId",
        "accessKey": "sample-accessKey",
        "adminId": 1,
        "adminName": "sample-adminName",
        "createdBy": "sample-createdBy",
        "createdOn": 1700000000,
        "id": 1,
        "lastAuthIp": "sample-lastAuthIp",
        "lastUsedOn": 1700000000,
        "note": "John Doe's API Token",
        "roles": [],
        "status": 2,
        "userPermission": "read"
      }
    ],
    "apionly": false,
    "contactMethod": "email",
    "createdBy": "Chief Admin",
    "email": "user@domain.com",
    "firstName": "John",
    "forcePasswordChange": true,
    "id": 1,
    "immediateForceLogout": false,
    "inactiveSessionTimeoutInSeconds": 1700000000,
    "lastAccessOn": 1700000000,
    "lastAction": "sample-lastAction",
    "lastActionOn": 1700000000,
    "lastActionOnLocal": "sample-lastActionOnLocal",
    "lastAuthIp": "sample-lastAuthIp",
    "lastLoginOn": 1700000000,
    "lastName": "Doe",
    "note": "John Doe is an Admin on this Portal",
    "password": "JohnDoe1",
    "persistentSessionEnabled": false,
    "phone": "8054445555",
    "roles": [
      {
        "acctRequireTwoFA": false,
        "associatedUserCount": 0,
        "customHelpLabel": "Internal Support Resources",
        "customHelpURL": "https://logicmonitor.com/support",
        "description": "Administrator can do everything, including security-sensitive actions",
        "enableRemoteSessionInCompanyLevel": false,
        "id": 1,
        "name": "administrator",
        "privileges": [],
        "requireEULA": true,
        "roleGroupId": 3,
        "twoFARequired": true,
        "userPermission": "read"
      }
    ],
    "smsEmail": "user@domain.com",
    "smsEmailFormat": "sms",
    "status": "active",
    "tenantId": 2,
    "timezone": "America/Los Angeles",
    "trainingEmail": "sample-trainingEmail",
    "twoFAEnabled": false,
    "userPermission": "read",
    "userType": "sample-userType",
    "username": "John",
    "viewPermission": "{\n\n\"Resources\" : true,\n\"Websites\" : true,\n\"Reports\" : true,\n\"Dashboards\" : true,\n\"Alerts\" : true,\n\"Settings\" : true,\n\"Maps\" : true,\n\"Logs\" : true,\n\"Traces\" : true\n\"Modules\" : true\n}"
  },
  Alert: {
    "SDT": {
      "empty": false
    },
    "ackComment": "sample-ackComment",
    "acked": false,
    "ackedBy": "sample-ackedBy",
    "ackedEpoch": 1700000000,
    "adAlert": false,
    "adAlertDesc": "sample-adAlertDesc",
    "alertExternalTicketUrl": {
      "empty": false
    },
    "alertGroupEntityValue": "sample-alertGroupEntityValue",
    "alertQuery": "sample-alertQuery",
    "alertTriggerValue": "sample-alertTriggerValue",
    "alertValue": "sample-alertValue",
    "anomaly": false,
    "chain": "sample-chain",
    "chainId": 1,
    "clearExpr": "sample-clearExpr",
    "clearValue": "sample-clearValue",
    "cleared": false,
    "context": {
      "activeOnly": false,
      "alertsById": {
        "alertRules": {},
        "alerts": {},
        "batchJobs": {},
        "billingAlerts": {},
        "billingAlertsMap": {},
        "budgets": {},
        "clusterAlertSettings": {},
        "dataSourceInstanceAlertSettings": {},
        "dataSourceInstances": {},
        "dataSources": {},
        "datapoints": {},
        "escalationChains": {},
        "eventSources": {},
        "logAlertsMap": {},
        "logalerts": {},
        "logpipelinesources": {},
        "resourceGroups": {},
        "resources": {},
        "sdts": {},
        "serviceCheckpoints": {},
        "serviceGroups": {},
        "services": {}
      },
      "anomaly": "sample-anomaly",
      "clearedOnly": false,
      "dependencyRoleFilters": [
        {}
      ],
      "dependencyRoleFiltersV4": [
        {}
      ],
      "dependencyRoutingStateFilters": [
        {}
      ],
      "dependencyRoutingStateFiltersV4": [
        {}
      ],
      "excludePhatomFlag": false,
      "forServices": false,
      "lmconfigEnabled": false,
      "pivotDimensionESField": [
        "sample-pivotDimensionESField"
      ],
      "pivotDimensions": [
        "sample-pivotDimensions"
      ],
      "pivotType": "sample-pivotType",
      "refreshActiveAlertCache": false,
      "suppressorFilters": [
        {}
      ],
      "suppressorFiltersV4": [
        {}
      ]
    },
    "dataPointId": 1,
    "dataPointName": "sample-dataPointName",
    "dependencyRole": "sample-dependencyRole",
    "dependencyRoutingState": "sample-dependencyRoutingState",
    "enableAnomalyAlertGeneration": "sample-enableAnomalyAlertGeneration",
    "enableAnomalyAlertSuppression": "sample-enableAnomalyAlertSuppression",
    "endEpoch": 1700000000,
    "id": "sample-id",
    "instanceDescription": "sample-instanceDescription",
    "instanceId": 1,
    "instanceName": "sample-instanceName",
    "internalId": "sample-internalId",
    "lastUpdatedOnEpoch": 1700000000,
    "logMetaData": "sample-logMetaData",
    "logPartition": "sample-logPartition",
    "monitorObjectGroups": {},
    "monitorObjectId": 1,
    "monitorObjectName": "sample-monitorObjectName",
    "monitorObjectType": "sample-monitorObjectType",
    "nextRecipient": 0,
    "receivedList": "sample-receivedList",
    "resourceId": 1,
    "resourceTemplateId": 1,
    "resourceTemplateName": "sample-resourceTemplateName",
    "resourceTemplateType": "sample-resourceTemplateType",
    "rule": "sample-rule",
    "ruleId": 1,
    "sdtIds": "sample-sdtIds",
    "sdted": {},
    "sessionId": 1,
    "severity": 0,
    "startEpoch": 1700000000,
    "subChainId": 1,
    "suppressDesc": "sample-suppressDesc",
    "suppressor": "sample-suppressor",
    "tenant": "sample-tenant",
    "threshold": "sample-threshold",
    "type": "sample-type"
  },
  AlertRule: {
    "datapoint": "*",
    "datasource": "Port-",
    "deviceGroups": "[Devices by Type]",
    "devices": "[Cisco Router]",
    "escalatingChain": {},
    "escalatingChainId": 12,
    "escalationInterval": 15,
    "id": 1,
    "instance": "*",
    "levelStr": "Warn",
    "name": "Warning",
    "priority": 100,
    "resourceProperties": [
      {
        "name": "sample-name",
        "value": "sample-value"
      }
    ],
    "sendAnomalySuppressedAlert": true,
    "suppressAlertAckSdt": true,
    "suppressAlertClear": true
  },
  Collector: {
    "ackComment": "sample-ackComment",
    "acked": false,
    "ackedBy": "sample-ackedBy",
    "ackedOn": 1700000000,
    "ackedOnLocal": "sample-ackedOnLocal",
    "agentConfFields": {},
    "arch": "sample-arch",
    "automaticUpgradeInfo": {
      "createdBy": "sample-createdBy",
      "dayOfWeek": "MON",
      "description": "regular MGD updates",
      "hour": 15,
      "level": "sample-level",
      "minute": 0,
      "occurrence": "Any",
      "timezone": "Americas/Los Angeles",
      "type": "sample-type",
      "version": "MGD"
    },
    "backupAgentId": 75,
    "bearerToken": "sample-bearerToken",
    "build": "sample-build",
    "calculatedThreshold": 0,
    "canDowngrade": false,
    "canDowngradeReason": "sample-canDowngradeReason",
    "clearSent": false,
    "collectorConf": "sample-collectorConf",
    "collectorDeviceId": 1,
    "collectorGroupId": 10,
    "collectorGroupName": "sample-collectorGroupName",
    "collectorList": "sample-collectorList",
    "collectorSize": "sample-collectorSize",
    "collectorType": "external",
    "confVersion": "sample-confVersion",
    "config": "sample-config",
    "copyUrl": "sample-copyUrl",
    "createdOn": 1700000000,
    "createdOnLocal": "sample-createdOnLocal",
    "customProperties": [
      {
        "name": "addr",
        "value": "127.0.0.1"
      }
    ],
    "description": "Linux Collector",
    "downloadUrl": "sample-downloadUrl",
    "ea": false,
    "enableFailBack": "true",
    "enableFailOverOnCollectorDevice": true,
    "enableLMLogs": false,
    "encodedConfigData": "sample-encodedConfigData",
    "errorMsg": "sample-errorMsg",
    "escalatingChainId": 80,
    "format": "sample-format",
    "hasFailOverDevice": false,
    "hostname": "sample-hostname",
    "id": 1,
    "inSDT": false,
    "isAdminAccount": false,
    "isDown": false,
    "isEncoded": false,
    "isLmlogsSyslogEnabled": false,
    "lastSentNotificationOn": 1700000000,
    "lastSentNotificationOnLocal": "sample-lastSentNotificationOnLocal",
    "needAutoCreateCollectorDevice": "true",
    "netscanVersion": "sample-netscanVersion",
    "nextRecipient": 0,
    "nextUpgradeInfo": {
      "majorVersion": 1700000000,
      "mandatory": false,
      "minorVersion": 1700000000,
      "stable": false,
      "upgradeTime": "sample-upgradeTime",
      "upgradeTimeEpoch": 1700000000
    },
    "numberOfHosts": 0,
    "numberOfInstances": 0,
    "numberOfSDTs": 0,
    "onetimeDowngradeInfo": {
      "createdBy": "sample-createdBy",
      "description": "regular MGD updates",
      "endEpoch": 1700000000,
      "level": "sample-level",
      "majorVersion": 27,
      "minorVersion": 1,
      "startEpoch": 1534888740,
      "timezone": "sample-timezone",
      "type": "sample-type"
    },
    "onetimeUpgradeInfo": {
      "createdBy": "sample-createdBy",
      "description": "regular MGD updates",
      "endEpoch": 1700000000,
      "level": "sample-level",
      "majorVersion": 27,
      "minorVersion": 1,
      "startEpoch": 1534888740,
      "timezone": "sample-timezone",
      "type": "sample-type"
    },
    "otelId": "sample-otelId",
    "otelVersion": "sample-otelVersion",
    "platform": "sample-platform",
    "predefinedConfig": {},
    "previousVersion": "sample-previousVersion",
    "resendIval": 15,
    "sbproxyConf": "sample-sbproxyConf",
    "specifiedCollectorDeviceGroupId": 0,
    "status": 0,
    "suppressAlertClear": true,
    "syntheticsEnabled": false,
    "upTime": 1700000000,
    "updatedOn": 1700000000,
    "updatedOnLocal": "sample-updatedOnLocal",
    "userChangeOn": 1700000000,
    "userChangeOnLocal": "sample-userChangeOnLocal",
    "userPermission": "sample-userPermission",
    "userVisibleHostsNum": 0,
    "watchdogConf": "sample-watchdogConf",
    "watchdogUpdatedOn": 1700000000,
    "watchdogUpdatedOnLocal": "sample-watchdogUpdatedOnLocal",
    "wrapperConf": "sample-wrapperConf"
  },
  CollectorGroup: {
    "autoBalance": false,
    "autoBalanceInstanceCountThreshold": 0,
    "autoBalanceStrategy": "sample-autoBalanceStrategy",
    "calThreshold": 0,
    "createOn": 1700000000,
    "customProperties": [
      {
        "name": "addr",
        "value": "127.0.0.1"
      }
    ],
    "description": "Group for collectors dedicated to Network Devices",
    "highestPriorityCollectorStatus": {
      "acked": false,
      "inSDT": false,
      "isDown": false,
      "status": 0
    },
    "id": 1,
    "mismatchVersion": false,
    "name": "Collector (Network Devices)",
    "numOfCollectors": 0,
    "numOfHosts": 0,
    "numOfInstances": 0,
    "platform": "sample-platform",
    "propertyForBalancing": "auto.collector.site.affinity.id",
    "propertyForBalancingLastUpdatedOn": 1700000000,
    "propertyForBalancingUpdateLockedUptoMS": 1700000000,
    "userPermission": "sample-userPermission"
  },
  ConfigSource: {
    "accessGroupIds": "1, 2, 3",
    "accessGroups": [
      {
        "createdBy": "sample-createdBy",
        "createdOn": 1700000000,
        "description": "Sample description",
        "id": 1,
        "name": "LinuxGroup",
        "tenantId": "sample-tenantId",
        "updatedOn": 1700000000
      }
    ],
    "adParameters": {
      "accessGroupIds": "1, 2, 3",
      "accessGroups": [
        {}
      ],
      "adParameters": {},
      "appliesTo": "sample-appliesTo",
      "auditVersion": 1700000000,
      "autoDiscoveryConfig": {
        "deleteInactiveInstance": false,
        "disableInstance": false,
        "filters": [],
        "instanceAutoGroupMethod": "sample-instanceAutoGroupMethod",
        "instanceAutoGroupMethodParams": "sample-instanceAutoGroupMethodParams",
        "method": {},
        "persistentInstance": false,
        "scheduleInterval": 0,
        "showDeletedInstanceDays": 0
      },
      "checksum": "sample-checksum",
      "collectInterval": 0,
      "collectMethod": "sample-collectMethod",
      "collectorAttribute": {
        "name": "sample-name"
      },
      "dataPoints": [
        {}
      ],
      "description": "Sample description",
      "displayName": "Sample Display Name",
      "enableAutoDiscovery": false,
      "enableEriDiscovery": false,
      "eriDiscoveryConfig": {
        "groovyScript": "sample-groovyScript",
        "linuxCmdline": "sample-linuxCmdline",
        "linuxScript": "sample-linuxScript",
        "name": "sample-name",
        "type": "sample-type",
        "winCmdline": "sample-winCmdline",
        "winScript": "sample-winScript"
      },
      "eriDiscoveryInterval": 0,
      "group": "sample-group",
      "hasMultiInstances": false,
      "id": 1,
      "installationMetadata": {
        "auditedRegistryId": "sample-auditedRegistryId",
        "auditedVersion": "sample-auditedVersion",
        "isChangedFromOrigin": false,
        "isChangedFromTargetLastPublished": false,
        "localModuleId": 1,
        "logicModuleType": "DATASOURCE",
        "originAuthorCompanyUUID": "sample-originAuthorCompanyUUID",
        "originAuthorNamespace": "sample-originAuthorNamespace",
        "originChecksum": "sample-originChecksum",
        "originLineageId": "sample-originLineageId",
        "originLocator": "sample-originLocator",
        "originName": "sample-originName",
        "originRegistryId": "sample-originRegistryId",
        "originVersion": "sample-originVersion",
        "targetLastPublishedChecksum": "sample-targetLastPublishedChecksum",
        "targetLastPublishedId": "sample-targetLastPublishedId",
        "targetLastPublishedVersion": "sample-targetLastPublishedVersion",
        "targetLineageId": "sample-targetLineageId"
      },
      "isInUse": false,
      "lineageId": "sample-lineageId",
      "name": "sample-name",
      "originRegistryId": "sample-originRegistryId",
      "payloadVersion": 1700000000,
      "tags": "sample-tags",
      "technology": "sample-technology",
      "useWildValueAsUUID": false,
      "version": 1700000000
    },
    "appliesTo": "sample-appliesTo",
    "auditVersion": 1700000000,
    "autoDiscoveryConfig": {
      "deleteInactiveInstance": false,
      "disableInstance": false,
      "filters": [
        {}
      ],
      "instanceAutoGroupMethod": "sample-instanceAutoGroupMethod",
      "instanceAutoGroupMethodParams": "sample-instanceAutoGroupMethodParams",
      "method": {
        "name": "sample-name"
      },
      "persistentInstance": false,
      "scheduleInterval": 0,
      "showDeletedInstanceDays": 0
    },
    "checksum": "sample-checksum",
    "collectInterval": 0,
    "collectMethod": "sample-collectMethod",
    "collectorAttribute": {
      "name": "sample-name"
    },
    "configChecks": [
      {
        "ackClearAlert": false,
        "alertEffectiveIval": 0,
        "alertLevel": 0,
        "alertTransitionInterval": 0,
        "configSourceId": 1,
        "description": "Sample description",
        "id": 1,
        "name": "sample-name",
        "originId": "sample-originId",
        "script": {},
        "type": "sample-type"
      }
    ],
    "description": "Sample description",
    "displayName": "Sample Display Name",
    "enableAutoDiscovery": false,
    "fileFormat": "sample-fileFormat",
    "group": "sample-group",
    "hasMultiInstances": false,
    "id": 1,
    "installationMetadata": {
      "auditedRegistryId": "sample-auditedRegistryId",
      "auditedVersion": "sample-auditedVersion",
      "isChangedFromOrigin": false,
      "isChangedFromTargetLastPublished": false,
      "localModuleId": 1,
      "logicModuleType": "DATASOURCE",
      "originAuthorCompanyUUID": "sample-originAuthorCompanyUUID",
      "originAuthorNamespace": "sample-originAuthorNamespace",
      "originChecksum": "sample-originChecksum",
      "originLineageId": "sample-originLineageId",
      "originLocator": "sample-originLocator",
      "originName": "sample-originName",
      "originRegistryId": "sample-originRegistryId",
      "originVersion": "sample-originVersion",
      "targetLastPublishedChecksum": "sample-targetLastPublishedChecksum",
      "targetLastPublishedId": "sample-targetLastPublishedId",
      "targetLastPublishedVersion": "sample-targetLastPublishedVersion",
      "targetLineageId": "sample-targetLineageId"
    },
    "isInUse": false,
    "lineageId": "sample-lineageId",
    "name": "sample-name",
    "originRegistryId": "sample-originRegistryId",
    "tags": "sample-tags",
    "technology": "sample-technology",
    "timestampFormat": "sample-timestampFormat",
    "version": 1700000000
  },
  Dashboard: {
    "defaultDashboardFilters": {
      "defaultDashboardFilterDetails": [
        {}
      ]
    },
    "description": "Windows Servers Performance",
    "fullName": "a new group//Collector Health/",
    "groupFullPath": "sample-groupFullPath",
    "groupId": 1,
    "groupName": "Server Dashboard",
    "id": 1,
    "name": "Default Device Group",
    "overwriteGroupFields": false,
    "owner": "sample-owner",
    "sharable": true,
    "template": {},
    "userPermission": "sample-userPermission",
    "widgetTokens": "\"[{\"name\":\"defaultDeviceGroup\",\"value\":\"*\"},{\"name\":\"defaultServiceGroup\",\"value\":\"*\"}]\"",
    "widgetsConfig": {}
  },
  DashboardGroup: {
    "dashboards": [
      {
        "id": 1,
        "name": "sample-name",
        "sharable": false,
        "userPermission": "sample-userPermission"
      }
    ],
    "description": "Servers in LA DataCenter",
    "fullPath": "sample-fullPath",
    "id": 1,
    "name": "LogicMonitor Dashboards",
    "numOfDashboards": 0,
    "numOfDirectDashboards": 0,
    "numOfDirectSubGroups": 0,
    "parentId": 1,
    "template": {},
    "userPermission": "sample-userPermission",
    "widgetTokens": [
      {
        "inheritList": [],
        "name": "Default Device Group",
        "type": "sample-type",
        "value": "Devices by Type/Network"
      }
    ]
  },
  DataSource: {
    "accessGroupIds": "1, 2, 3",
    "accessGroups": [
      {
        "createdBy": "sample-createdBy",
        "createdOn": 1700000000,
        "description": "Sample description",
        "id": 1,
        "name": "LinuxGroup",
        "tenantId": "sample-tenantId",
        "updatedOn": 1700000000
      }
    ],
    "adParameters": {
      "accessGroupIds": "1, 2, 3",
      "accessGroups": [
        {}
      ],
      "adParameters": {},
      "appliesTo": "sample-appliesTo",
      "auditVersion": 1700000000,
      "autoDiscoveryConfig": {
        "deleteInactiveInstance": false,
        "disableInstance": false,
        "filters": [],
        "instanceAutoGroupMethod": "sample-instanceAutoGroupMethod",
        "instanceAutoGroupMethodParams": "sample-instanceAutoGroupMethodParams",
        "method": {},
        "persistentInstance": false,
        "scheduleInterval": 0,
        "showDeletedInstanceDays": 0
      },
      "checksum": "sample-checksum",
      "collectInterval": 0,
      "collectMethod": "sample-collectMethod",
      "collectorAttribute": {
        "name": "sample-name"
      },
      "dataPoints": [
        {}
      ],
      "description": "Sample description",
      "displayName": "Sample Display Name",
      "enableAutoDiscovery": false,
      "enableEriDiscovery": false,
      "eriDiscoveryConfig": {
        "groovyScript": "sample-groovyScript",
        "linuxCmdline": "sample-linuxCmdline",
        "linuxScript": "sample-linuxScript",
        "name": "sample-name",
        "type": "sample-type",
        "winCmdline": "sample-winCmdline",
        "winScript": "sample-winScript"
      },
      "eriDiscoveryInterval": 0,
      "group": "sample-group",
      "hasMultiInstances": false,
      "id": 1,
      "installationMetadata": {
        "auditedRegistryId": "sample-auditedRegistryId",
        "auditedVersion": "sample-auditedVersion",
        "isChangedFromOrigin": false,
        "isChangedFromTargetLastPublished": false,
        "localModuleId": 1,
        "logicModuleType": "DATASOURCE",
        "originAuthorCompanyUUID": "sample-originAuthorCompanyUUID",
        "originAuthorNamespace": "sample-originAuthorNamespace",
        "originChecksum": "sample-originChecksum",
        "originLineageId": "sample-originLineageId",
        "originLocator": "sample-originLocator",
        "originName": "sample-originName",
        "originRegistryId": "sample-originRegistryId",
        "originVersion": "sample-originVersion",
        "targetLastPublishedChecksum": "sample-targetLastPublishedChecksum",
        "targetLastPublishedId": "sample-targetLastPublishedId",
        "targetLastPublishedVersion": "sample-targetLastPublishedVersion",
        "targetLineageId": "sample-targetLineageId"
      },
      "isInUse": false,
      "lineageId": "sample-lineageId",
      "name": "sample-name",
      "originRegistryId": "sample-originRegistryId",
      "payloadVersion": 1700000000,
      "tags": "sample-tags",
      "technology": "sample-technology",
      "useWildValueAsUUID": false,
      "version": 1700000000
    },
    "appliesTo": "sample-appliesTo",
    "auditVersion": 1700000000,
    "autoDiscoveryConfig": {
      "deleteInactiveInstance": false,
      "disableInstance": false,
      "filters": [
        {}
      ],
      "instanceAutoGroupMethod": "sample-instanceAutoGroupMethod",
      "instanceAutoGroupMethodParams": "sample-instanceAutoGroupMethodParams",
      "method": {
        "name": "sample-name"
      },
      "persistentInstance": false,
      "scheduleInterval": 0,
      "showDeletedInstanceDays": 0
    },
    "checksum": "sample-checksum",
    "collectInterval": 0,
    "collectMethod": "sample-collectMethod",
    "collectorAttribute": {
      "name": "sample-name"
    },
    "dataPoints": [
      {
        "adAdvSettingEnabled": false,
        "alertBody": "sample-alertBody",
        "alertClearTransitionInterval": 0,
        "alertExpr": "sample-alertExpr",
        "alertExprNote": "sample-alertExprNote",
        "alertForNoData": 0,
        "alertSubject": "sample-alertSubject",
        "alertTransitionInterval": 0,
        "criticalAdAdvSetting": "sample-criticalAdAdvSetting",
        "dataSourceId": 1,
        "dataType": 0,
        "description": "Sample description",
        "enableAnomalyAlertSuppression": "sample-enableAnomalyAlertSuppression",
        "errorAdAdvSetting": "sample-errorAdAdvSetting",
        "id": 1,
        "maxDigits": 0,
        "maxValue": "sample-maxValue",
        "minValue": "sample-minValue",
        "name": "sample-name",
        "originId": "sample-originId",
        "postProcessorMethod": "sample-postProcessorMethod",
        "postProcessorParam": "sample-postProcessorParam",
        "rawDataFieldName": "sample-rawDataFieldName",
        "statusDisplayNames": [],
        "type": 0,
        "userParam1": "sample-userParam1",
        "userParam2": "sample-userParam2",
        "userParam3": "sample-userParam3",
        "warnAdAdvSetting": "sample-warnAdAdvSetting"
      }
    ],
    "description": "Sample description",
    "displayName": "Sample Display Name",
    "enableAutoDiscovery": false,
    "enableEriDiscovery": false,
    "eriDiscoveryConfig": {
      "groovyScript": "sample-groovyScript",
      "linuxCmdline": "sample-linuxCmdline",
      "linuxScript": "sample-linuxScript",
      "name": "sample-name",
      "type": "sample-type",
      "winCmdline": "sample-winCmdline",
      "winScript": "sample-winScript"
    },
    "eriDiscoveryInterval": 0,
    "group": "sample-group",
    "hasMultiInstances": false,
    "id": 1,
    "installationMetadata": {
      "auditedRegistryId": "sample-auditedRegistryId",
      "auditedVersion": "sample-auditedVersion",
      "isChangedFromOrigin": false,
      "isChangedFromTargetLastPublished": false,
      "localModuleId": 1,
      "logicModuleType": "DATASOURCE",
      "originAuthorCompanyUUID": "sample-originAuthorCompanyUUID",
      "originAuthorNamespace": "sample-originAuthorNamespace",
      "originChecksum": "sample-originChecksum",
      "originLineageId": "sample-originLineageId",
      "originLocator": "sample-originLocator",
      "originName": "sample-originName",
      "originRegistryId": "sample-originRegistryId",
      "originVersion": "sample-originVersion",
      "targetLastPublishedChecksum": "sample-targetLastPublishedChecksum",
      "targetLastPublishedId": "sample-targetLastPublishedId",
      "targetLastPublishedVersion": "sample-targetLastPublishedVersion",
      "targetLineageId": "sample-targetLineageId"
    },
    "isInUse": false,
    "lineageId": "sample-lineageId",
    "name": "sample-name",
    "originRegistryId": "sample-originRegistryId",
    "payloadVersion": 1700000000,
    "tags": "sample-tags",
    "technology": "sample-technology",
    "useWildValueAsUUID": false,
    "version": 1700000000
  },
  Device: {
    "autoBalancedCollectorGroupId": 1,
    "autoProperties": [
      {
        "name": "addr",
        "value": "127.0.0.1"
      }
    ],
    "autoPropsAssignedOn": 1700000000,
    "autoPropsUpdatedOn": 1700000000,
    "awsState": 0,
    "azureState": 0,
    "collectorDescription": "sample-collectorDescription",
    "containsMultiValue": false,
    "createdOn": 1700000000,
    "currentCollectorId": 1,
    "currentLogCollectorId": 1,
    "customProperties": [
      {
        "name": "addr",
        "value": "127.0.0.1"
      }
    ],
    "deletedTimeInMs": 1700000000,
    "description": "This is a Cisco Router",
    "deviceType": 0,
    "disableAlerting": true,
    "displayName": "Cisco Router",
    "enableNetflow": true,
    "gcpState": 0,
    "hostGroupIds": "16,4,3",
    "hostStatus": "sample-hostStatus",
    "id": 1,
    "inheritedProperties": [
      {
        "name": "addr",
        "value": "127.0.0.1"
      }
    ],
    "isPreferredLogCollectorConfigured": true,
    "lastDataTime": 1700000000,
    "lastRawdataTime": 1700000000,
    "link": "www.ciscorouter.com",
    "logCollectorDescription": "sample-logCollectorDescription",
    "logCollectorGroupId": 1,
    "logCollectorGroupName": "sample-logCollectorGroupName",
    "logCollectorId": 1,
    "name": "Main Collector",
    "netflowCollectorDescription": "sample-netflowCollectorDescription",
    "netflowCollectorGroupId": 1,
    "netflowCollectorGroupName": "sample-netflowCollectorGroupName",
    "netflowCollectorId": 1,
    "op": "sample-op",
    "preferredCollectorGroupId": 1,
    "preferredCollectorGroupName": "sample-preferredCollectorGroupName",
    "preferredCollectorId": 2,
    "relatedDeviceId": -1,
    "resourceIds": [
      {
        "name": "addr",
        "value": "127.0.0.1"
      }
    ],
    "rolePrivileges": [
      "sample-rolePrivileges"
    ],
    "scanConfigId": 0,
    "syntheticsCollectorIds": "1,4",
    "systemProperties": [
      {
        "name": "addr",
        "value": "127.0.0.1"
      }
    ],
    "toDeleteTimeInMs": 1700000000,
    "type": "uptimewebcheck",
    "upTimeInSeconds": 1700000000,
    "updatedOn": 1700000000,
    "userPermission": "sample-userPermission"
  },
  DeviceGroup: {
    "appliesTo": "isLinux()",
    "awsRegionsInfo": "sample-awsRegionsInfo",
    "awsTestResult": {
      "detailLink": "sample-detailLink",
      "noPermissionServices": [
        "sample-noPermissionServices"
      ],
      "nonPermissionErrors": [
        "sample-nonPermissionErrors"
      ],
      "warnings": [
        "CLIENT_ID_ISSUE"
      ]
    },
    "awsTestResultCode": 0,
    "azureRegionsInfo": "sample-azureRegionsInfo",
    "azureTestResult": {
      "detailLink": {},
      "noPermissionServices": {}
    },
    "azureTestResultCode": 0,
    "createdOn": 1700000000,
    "customProperties": [
      {
        "name": "addr",
        "value": "127.0.0.1"
      }
    ],
    "defaultAutoBalancedCollectorGroupId": 1,
    "defaultCollectorDescription": "sample-defaultCollectorDescription",
    "defaultCollectorGroupDescription": "sample-defaultCollectorGroupDescription",
    "defaultCollectorGroupId": 1,
    "defaultCollectorId": 1,
    "description": "Linux Servers",
    "disableAlerting": true,
    "effectiveAlertEnabled": false,
    "enableNetflow": "true",
    "extra": {},
    "fullPath": "sample-fullPath",
    "gcpRegionsInfo": "sample-gcpRegionsInfo",
    "gcpTestResult": {
      "detailLink": "sample-detailLink",
      "noPermissionServices": [
        "sample-noPermissionServices"
      ],
      "nonPermissionErrors": [
        "sample-nonPermissionErrors"
      ]
    },
    "gcpTestResultCode": 0,
    "groupStatus": "sample-groupStatus",
    "groupType": "Normal",
    "hasNetflowEnabledDevices": false,
    "id": 1,
    "name": "Linux Servers",
    "numOfAWSDevices": 0,
    "numOfAzureDevices": 0,
    "numOfDirectDevices": 0,
    "numOfDirectSubGroups": 0,
    "numOfGcpDevices": 0,
    "numOfHosts": 0,
    "numOfKubernetesDevices": 0,
    "numOfOciDevices": 0,
    "ociRegionsInfo": "sample-ociRegionsInfo",
    "ociTestResult": {
      "noPermissionServices": [
        "sample-noPermissionServices"
      ],
      "nonPermissionErrors": [
        "sample-nonPermissionErrors"
      ]
    },
    "ociTestResultCode": 0,
    "parentId": 1,
    "propertyChangeWarningMessage": "sample-propertyChangeWarningMessage",
    "rolePrivileges": [
      "sample-rolePrivileges"
    ],
    "saasTestResult": {
      "detailLink": "sample-detailLink",
      "invalidStatusUrls": "sample-invalidStatusUrls",
      "noPermissionApis": [
        "sample-noPermissionApis"
      ],
      "noPermissionService": "sample-noPermissionService",
      "nonPermissionApisErrors": [
        "sample-nonPermissionApisErrors"
      ],
      "resultCode": 0
    },
    "saasTestResultCode": 0,
    "subGroups": [
      {
        "appliesTo": "sample-appliesTo",
        "awsRegionsInfo": "sample-awsRegionsInfo",
        "azureRegionsInfo": "sample-azureRegionsInfo",
        "description": "Sample description",
        "fullPath": "sample-fullPath",
        "gcpRegionsInfo": "sample-gcpRegionsInfo",
        "groupType": "sample-groupType",
        "id": 1,
        "name": "sample-name",
        "numOfDirectDevices": 0,
        "numOfDirectSubGroups": 0,
        "numOfHosts": 0,
        "ociRegionsInfo": "sample-ociRegionsInfo",
        "rolePrivileges": [],
        "userPermission": "sample-userPermission"
      }
    ],
    "userPermission": "sample-userPermission"
  },
  EscalationChain: {
    "ccDestinations": [
      {
        "addr": "user@domain.com",
        "contact": "sample-contact",
        "method": "EMAIL",
        "type": "Admin"
      }
    ],
    "description": "For alerts escalated to the NOC Team",
    "destinations": [
      {
        "period": {},
        "stages": [],
        "type": "sample-type"
      }
    ],
    "enableThrottling": true,
    "id": 1,
    "inAlerting": false,
    "name": "NOC Team",
    "throttlingAlerts": 40,
    "throttlingPeriod": 30
  },
  EventSource: {
    "accessGroupIds": "1, 2, 3",
    "accessGroups": [
      {
        "createdBy": "sample-createdBy",
        "createdOn": 1700000000,
        "description": "Sample description",
        "id": 1,
        "name": "LinuxGroup",
        "tenantId": "sample-tenantId",
        "updatedOn": 1700000000
      }
    ],
    "alertBodyTemplate": "sample-alertBodyTemplate",
    "alertEffectiveIval": 0,
    "alertLevel": "sample-alertLevel",
    "alertSubjectTemplate": "sample-alertSubjectTemplate",
    "appliesTo": "sample-appliesTo",
    "auditVersion": 1700000000,
    "checksum": "sample-checksum",
    "clearAfterAck": false,
    "collector": "sample-collector",
    "description": "Sample description",
    "eventSource": {
      "accessGroupIds": "1, 2, 3",
      "accessGroups": [
        {}
      ],
      "alertBodyTemplate": "sample-alertBodyTemplate",
      "alertEffectiveIval": 0,
      "alertLevel": "sample-alertLevel",
      "alertSubjectTemplate": "sample-alertSubjectTemplate",
      "appliesTo": "sample-appliesTo",
      "auditVersion": 1700000000,
      "checksum": "sample-checksum",
      "clearAfterAck": false,
      "collector": "sample-collector",
      "description": "Sample description",
      "eventSource": {},
      "eventSourceFilters": [
        {}
      ],
      "filters": [
        {}
      ],
      "group": "sample-group",
      "id": 1,
      "installationMetadata": {
        "auditedRegistryId": "sample-auditedRegistryId",
        "auditedVersion": "sample-auditedVersion",
        "isChangedFromOrigin": false,
        "isChangedFromTargetLastPublished": false,
        "localModuleId": 1,
        "logicModuleType": "DATASOURCE",
        "originAuthorCompanyUUID": "sample-originAuthorCompanyUUID",
        "originAuthorNamespace": "sample-originAuthorNamespace",
        "originChecksum": "sample-originChecksum",
        "originLineageId": "sample-originLineageId",
        "originLocator": "sample-originLocator",
        "originName": "sample-originName",
        "originRegistryId": "sample-originRegistryId",
        "originVersion": "sample-originVersion",
        "targetLastPublishedChecksum": "sample-targetLastPublishedChecksum",
        "targetLastPublishedId": "sample-targetLastPublishedId",
        "targetLastPublishedVersion": "sample-targetLastPublishedVersion",
        "targetLineageId": "sample-targetLineageId"
      },
      "isInUse": false,
      "lineageId": "sample-lineageId",
      "name": "sample-name",
      "originRegistryId": "sample-originRegistryId",
      "suppressDuplicatesES": false,
      "tags": "sample-tags",
      "technology": "sample-technology",
      "version": 1700000000
    },
    "eventSourceFilters": [
      {
        "comment": "sample-comment",
        "eventSourceId": 1,
        "id": 1,
        "name": "sample-name",
        "op": "sample-op",
        "originId": "sample-originId",
        "value": "sample-value"
      }
    ],
    "filters": [
      {
        "comment": "sample-comment",
        "id": 1,
        "name": "sample-name",
        "operator": "sample-operator",
        "value": "sample-value"
      }
    ],
    "group": "sample-group",
    "id": 1,
    "installationMetadata": {
      "auditedRegistryId": "sample-auditedRegistryId",
      "auditedVersion": "sample-auditedVersion",
      "isChangedFromOrigin": false,
      "isChangedFromTargetLastPublished": false,
      "localModuleId": 1,
      "logicModuleType": "DATASOURCE",
      "originAuthorCompanyUUID": "sample-originAuthorCompanyUUID",
      "originAuthorNamespace": "sample-originAuthorNamespace",
      "originChecksum": "sample-originChecksum",
      "originLineageId": "sample-originLineageId",
      "originLocator": "sample-originLocator",
      "originName": "sample-originName",
      "originRegistryId": "sample-originRegistryId",
      "originVersion": "sample-originVersion",
      "targetLastPublishedChecksum": "sample-targetLastPublishedChecksum",
      "targetLastPublishedId": "sample-targetLastPublishedId",
      "targetLastPublishedVersion": "sample-targetLastPublishedVersion",
      "targetLineageId": "sample-targetLineageId"
    },
    "isInUse": false,
    "lineageId": "sample-lineageId",
    "name": "sample-name",
    "originRegistryId": "sample-originRegistryId",
    "suppressDuplicatesES": false,
    "tags": "sample-tags",
    "technology": "sample-technology",
    "version": 1700000000
  },
  OpsNote: {
    "createdBy": "sample-createdBy",
    "happenOnInSec": 1488826440,
    "id": "sample-id",
    "note": "software update from 1.0.0 to 1.2.4",
    "scopes": [
      {
        "type": "device"
      }
    ],
    "tags": [
      {
        "createdOnInSec": 1700000000,
        "id": "sample-id",
        "name": "sample-name",
        "updateOnInSec": 1700000000
      }
    ]
  },
  RecipientGroup: {
    "description": "Tier 1 Helpdesk",
    "groupName": "Tier 1 Helpdesk",
    "id": 1,
    "recipients": [
      {
        "addr": "user@domain.com",
        "contact": "sample-contact",
        "method": "EMAIL",
        "type": "Admin"
      }
    ]
  },
  Report: {
    "customReportTypeId": 1,
    "customReportTypeName": "sample-customReportTypeName",
    "delivery": "email",
    "description": "This is a daily alerts report",
    "enableViewAsOtherUser": false,
    "format": "HTML",
    "groupId": 5,
    "id": 1,
    "lastGenerateOn": 1700000000,
    "lastGeneratePages": 0,
    "lastGenerateSize": 0,
    "lastmodifyUserId": 1,
    "lastmodifyUserName": "sample-lastmodifyUserName",
    "name": "Daily Alerts Report",
    "recipients": [
      {
        "additionInfo": "sample-additionInfo",
        "addr": "sarah",
        "method": "email",
        "type": "admin"
      }
    ],
    "reportLinkExpire": "High Flexibility",
    "reportLinkNum": 0,
    "schedule": "0 7 * * 1",
    "scheduleTimezone": "America/Los_Angeles",
    "type": "Alert",
    "userPermission": "sample-userPermission"
  },
  Role: {
    "acctRequireTwoFA": false,
    "associatedUserCount": 0,
    "customHelpLabel": "Internal Support Resources",
    "customHelpURL": "https://logicmonitor.com/support",
    "description": "Administrator can do everything, including security-sensitive actions",
    "enableRemoteSessionInCompanyLevel": false,
    "id": 1,
    "name": "administrator",
    "privileges": [
      {
        "objectId": "123",
        "objectName": "sample-objectName",
        "objectType": "dashboard group",
        "operation": "write",
        "subOperation": "sample-subOperation"
      }
    ],
    "requireEULA": true,
    "roleGroupId": 3,
    "twoFARequired": true,
    "userPermission": "read"
  },
  SDT: {
    "admin": "sample-admin",
    "comment": "Emergency prod deployment",
    "defaultValue": "2024-01-01T00:00:00Z",
    "duration": 138,
    "endDateTime": 1534554000000,
    "endDateTimeOnLocal": "sample-endDateTimeOnLocal",
    "endHour": 5,
    "endMinute": 18,
    "hour": 3,
    "id": "sample-id",
    "isEffective": false,
    "minute": 6,
    "monthDay": 7,
    "sdtType": "oneTime",
    "startDateTime": 1534460400000,
    "startDateTimeOnLocal": "sample-startDateTimeOnLocal",
    "timezone": "America/Los_Angeles",
    "type": "ResourceGroupSDT",
    "weekDay": "Sunday",
    "weekOfMonth": "1"
  },
  Website: {
    "checkpoints": [
      {
        "geoInfo": "sample-geoInfo",
        "id": 1,
        "smgId": 1
      }
    ],
    "collectors": [
      {
        "collectorGroupId": 1,
        "collectorGroupName": "sample-collectorGroupName",
        "description": "Sample description",
        "hostname": "sample-hostname",
        "id": 1,
        "status": "sample-status"
      }
    ],
    "description": "Monitor Ebay site response times",
    "disableAlerting": false,
    "domain": "www.ebay.com",
    "globalSmAlertCond": 0,
    "groupId": 1,
    "id": 1,
    "individualAlertLevel": "warn",
    "individualSmAlertEnable": false,
    "isInternal": false,
    "lastUpdated": 1700000000,
    "name": "Ebay",
    "overallAlertLevel": "warn",
    "pollingInterval": 5,
    "properties": [
      {
        "name": "addr",
        "value": "127.0.0.1"
      }
    ],
    "rolePrivileges": [
      "sample-rolePrivileges"
    ],
    "status": "sample-status",
    "steps": [
      {
        "HTTPBody": "sample-HTTPBody",
        "HTTPHeaders": "sample-HTTPHeaders",
        "HTTPMethod": "GET",
        "HTTPVersion": "1.1",
        "auth": {},
        "description": "Sample description",
        "enable": false,
        "followRedirection": "true",
        "fullpageLoad": false,
        "invertMatch": false,
        "keyword": "sample-keyword",
        "label": "sample-label",
        "matchType": "plain",
        "name": "sample-name",
        "path": "sample-path",
        "postDataEditType": "raw",
        "reqScript": "sample-reqScript",
        "reqType": "sample-reqType",
        "requireAuth": false,
        "respScript": "sample-respScript",
        "respType": "sample-respType",
        "schema": "sample-schema",
        "statusCode": "sample-statusCode",
        "timeout": 1700000000,
        "type": "config",
        "url": "/",
        "useDefaultRoot": "true"
      }
    ],
    "stopMonitoring": false,
    "stopMonitoringByFolder": false,
    "template": {},
    "testLocation": {
      "all": "true",
      "collectorIds": [
        1
      ],
      "collectors": [
        {}
      ],
      "smgIds": "[1, 2, 4, 3, 5, 6]"
    },
    "transition": 1,
    "type": "webcheck",
    "useDefaultAlertSetting": true,
    "useDefaultLocationSetting": false,
    "userPermission": "sample-userPermission"
  },
  WebsiteGroup: {
    "description": "Amazon web and ping checks",
    "disableAlerting": false,
    "fullPath": "sample-fullPath",
    "hasWebsitesDisabled": false,
    "id": 1,
    "name": "Amazon Website Checks",
    "numOfDirectSubGroups": 0,
    "numOfDirectWebsites": 0,
    "numOfWebsites": 0,
    "parentId": 1,
    "properties": [
      {
        "name": "addr",
        "value": "127.0.0.1"
      }
    ],
    "rolePrivileges": [
      "sample-rolePrivileges"
    ],
    "stopMonitoring": false,
    "testLocation": {
      "all": "true",
      "collectorIds": [
        1
      ],
      "collectors": [
        {}
      ],
      "smgIds": "[1, 2, 4, 3, 5, 6]"
    },
    "userPermission": "sample-userPermission"
  },
  Widget: {
    "dashboardId": 1,
    "description": "Devices By Type",
    "id": 1,
    "interval": 5,
    "isSupportCustomProperty": false,
    "lastUpdatedBy": "sample-lastUpdatedBy",
    "lastUpdatedOn": 1700000000,
    "name": "Test",
    "supportCustomProperty": false,
    "theme": "newBorderBlue",
    "timescale": "sample-timescale",
    "type": "bigNumber",
    "userPermission": "write"
  },
} as const;

/** Union of available fixture model names. */
export type LMFixtureModel = keyof typeof LM_FIXTURES;
